In [1]:
import tensorflow as tf

In [2]:
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

In [3]:
x = tf.random_uniform(shape=[10], minval=0, maxval=1.0, 
                      dtype=tf.float32, seed=125, name='X')
y = tf.random_uniform(shape=[10], minval = 0, maxval = 1.0, dtype = tf.float32,
                     seed = 33, name = 'Y')
comparison = tf.where(tf.greater(x,y), x = tf.add(x, y), y = tf.subtract(x, y), 
                      name = 'condition')

In [4]:
with tf.Session() as sess:
    writer  =  tf.summary.FileWriter ( './tfGraphs' ,  sess.graph)
    print sess.run([x,y,comparison])
    writer.close()

[array([ 0.28615248,  0.96822393,  0.17870843,  0.87988698,  0.09727454,
        0.46245158,  0.82588065,  0.16126847,  0.29832828,  0.95451784], dtype=float32), array([ 0.05454671,  0.32781899,  0.19744873,  0.73043966,  0.94582987,
        0.15157604,  0.76446605,  0.21702075,  0.51217759,  0.60553586], dtype=float32), array([ 0.3406992 ,  1.29604292, -0.0187403 ,  1.61032665, -0.84855533,
        0.61402762,  1.59034669, -0.05575228, -0.21384931,  1.56005371], dtype=float32)]


In [ ]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

In [31]:
x = tf.random_uniform(shape=[], minval=-1.0, maxval=1.0, 
                      dtype=tf.float32, seed=11, name='X')
y = tf.random_uniform(shape=[], minval = -1.0, maxval = 1.0, dtype = tf.float32,
                      seed=11,name = 'Y')
#pair = tf.tuple()
case = tf.case({tf.less(x,y) : lambda: tf.add(x,y),
               tf.greater(x,y) : lambda: tf.subtract(x,y)}, default = lambda: tf.constant(0.0), 
                      name = 'condition',exclusive = True)

In [32]:
with tf.Session() as sess:
    writer  =  tf.summary.FileWriter ( './tfGraphs' ,  sess.graph)
    print sess.run([x,y,case])
    writer.close()

[-0.82089829, -0.82089829, 0.0]


In [ ]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

In [40]:
x = tf.constant([[0, -2, -1], [0, 1, 2]] , dtype =tf.int8, name = 'x')
y = tf.zeros_like(x, dtype = tf.int8, name = 'y')
equality = tf.equal(x,y)

In [41]:
with tf.Session() as sess:
    writer  =  tf.summary.FileWriter ( './tfGraphs' ,  sess.graph)
    print sess.run(equality)
    writer.close()

[[ True False False]
 [ True False False]]


In [42]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################

In [48]:
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
                 30.97266006,  26.67541885,  38.08450317,  20.74983215,
                 34.94445419,  34.45999146,  29.06485367,  36.01657104,
                 27.88236427,  20.56035233,  30.20379066,  29.51215172,
                 33.71149445,  28.59134293,  36.05556488,  28.66994858],
               dtype=tf.float32, name = 'X')
indices_more_30 = tf.where(tf.greater(x,tf.constant(30.0)))
gather_more_30 = tf.gather(x,indices=indices_more_30)

In [49]:
with tf.Session() as sess:
    writer  =  tf.summary.FileWriter ( './tfGraphs' ,  sess.graph)
    print sess.run([indices_more_30,gather_more_30])
    writer.close()

[array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [ 9],
       [11],
       [14],
       [16],
       [18]]), array([[ 31.19073486],
       [ 30.97266006],
       [ 38.08450317],
       [ 34.94445419],
       [ 34.45999146],
       [ 36.01657104],
       [ 30.20379066],
       [ 33.71149445],
       [ 36.05556488]], dtype=float32)]


In [50]:
## !! also a possibility for comparisons 
x > 30

<tf.Tensor 'Greater_13:0' shape=(20,) dtype=bool>

In [51]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################

In [57]:
x = tf.diag(tf.range(start=1,limit=7))

In [58]:
with tf.Session() as sess:
    writer  =  tf.summary.FileWriter ( './tfGraphs' ,  sess.graph)
    print sess.run(x)
    writer.close()

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [53]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

In [65]:
x = tf.random_gamma(shape=[10,10],alpha=2.0,beta=2.5,name='X')
determinant = tf.matrix_determinant(x)

In [67]:
with tf.Session() as sess:
    writer  =  tf.summary.FileWriter ( './tfGraphs' ,  sess.graph)
    l =  sess.run([x, determinant])
    print l[0]
    print l[1]
    writer.close()

[[ 0.80692804  0.3741377   0.4623805   0.1549596   0.93460637  0.42806253
   0.4993287   0.1744357   0.64519316  1.41615546]
 [ 0.56360704  0.73262393  0.37322125  0.87185591  0.62820095  0.34388787
   1.75967383  1.06596017  1.46449804  0.20796402]
 [ 0.57885897  0.2415435   0.29209411  0.94754255  0.81880027  0.37840807
   0.69699937  1.01190186  1.6937058   0.36817667]
 [ 0.33718824  0.41436052  0.25450772  0.65604156  1.80764866  1.06091857
   1.23130322  1.45585608  0.73065937  0.56665683]
 [ 1.03430712  1.28045988  0.87275064  0.77493787  1.80405486  0.28444278
   0.11120697  0.40091261  1.11819243  1.30559754]
 [ 0.58973056  0.1718674   1.18047154  1.21719456  0.44118699  0.19843915
   0.3305282   0.23890701  0.73479825  0.40973538]
 [ 0.25493842  0.53213382  1.34317994  2.97683692  1.04615188  0.3719629
   0.62576157  0.68872076  0.98723173  0.77763903]
 [ 0.71731997  0.90300703  0.82966727  0.58443296  0.88604707  0.52952087
   0.84950173  0.62834471  0.1522111   1.17506146]
 

In [68]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

In [71]:
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9],name='X')
unique_x = tf.unique(x,name='uniqueX')[0]

In [72]:
with tf.Session() as sess:
    writer  =  tf.summary.FileWriter ( './tfGraphs' ,  sess.graph)
    print sess.run(unique_x)
    writer.close()

[ 5  2  3 10  6  4  1  0  9]


In [73]:
unique_x # still a tensor from the tuple

<tf.Tensor 'uniqueX_1:0' shape=(?,) dtype=int32>

In [74]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or => interpreted as a standard deviation
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################

In [82]:
x = tf.random_normal([300], mean=0.0, stddev=1.0,name='x')
y = tf.random_normal([300], mean=0.0, stddev=1.0,name='y')
xyDiff = tf.subtract(x,y,name='xyDiff')
output = tf.cond(tf.reduce_mean(xyDiff) < 0, 
                 lambda: tf.reduce_mean(tf.pow(
                        xyDiff-tf.reduce_mean(xyDiff),2.0)),
                lambda: tf.reduce_sum(tf.abs(xyDiff)))

In [89]:
with tf.Session() as sess:
    writer  =  tf.summary.FileWriter ( './tfGraphs' ,  sess.graph)
    print sess.run(output)
    writer.close()

1.9347


In [ ]:
# the ''official'' solution
x = tf.random_normal([300], mean=5, stddev=1)
y = tf.random_normal([300], mean=5, stddev=1)
average = tf.reduce_mean(x - y)
def f1(): return tf.reduce_mean(tf.square(x - y))
def f2(): return tf.reduce_sum(tf.abs(x - y))
out = tf.cond(average < 0, f1, f2)